fix NoClassDefFoundError: javax/servlet/Filter in Sonar analysis with Maven
https://community.sonarsource.com/t/sonarqube-10-3-sonar-maven-required-class-was-missing-javax-servlet-filter/107677/19